services:
  - type: web
    name: campus-diary-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: IS_RENDER
        value: true
      - key: PORT
        value: 8000
    disk:
      name: data
      mountPath: /data
      sizeGB: 1